ignoreScripts: true
minimumReleaseAge: 0
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@trickfilm400/rollup-plugin-off-main-thread@3.0.0-pre1"
  - semver@6.3.1
packages: [.]
overrides:
  is-core-module: "npm:@nolyfill/is-core-module@^1"
  string.prototype.matchall: "npm:@nolyfill/string.prototype.matchall@^1"
  ws@>=8.0.0 <8.21.0: ^8.21.0
