/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    'Calendar': RouteRecordInfo<'Calendar', '/calendar', Record<never, never>, Record<never, never>, 'Calendar Month' | 'Calendar Week' | 'Calendar Year'>,
    'Calendar Month': RouteRecordInfo<'Calendar Month', '/calendar/month', Record<never, never>, Record<never, never>>,
    'Calendar Week': RouteRecordInfo<'Calendar Week', '/calendar/week', Record<never, never>, Record<never, never>>,
    'Calendar Year': RouteRecordInfo<'Calendar Year', '/calendar/year', Record<never, never>, Record<never, never>>,
    'Constellations': RouteRecordInfo<'Constellations', '/constellations', Record<never, never>, Record<never, never>>,
    'Constellations Month': RouteRecordInfo<'Constellations Month', '/constellations/:month', { month: ParamValue<true> }, { month: ParamValue<false> }>,
    'Holiday': RouteRecordInfo<'Holiday', '/holiday', Record<never, never>, Record<never, never>>,
    'Moon Phase': RouteRecordInfo<'Moon Phase', '/moon-phase', Record<never, never>, Record<never, never>>,
    'Onboarding': RouteRecordInfo<'Onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'Search': RouteRecordInfo<'Search', '/search', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    'Summoning Day': RouteRecordInfo<'Summoning Day', '/summoning-day', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'Home'
      views: never
    }
    'src/pages/calendar.vue': {
      routes: 'Calendar' | 'Calendar Month' | 'Calendar Week' | 'Calendar Year'
      views: 'default'
    }
    'src/pages/calendar/month.vue': {
      routes: 'Calendar Month'
      views: never
    }
    'src/pages/calendar/week.vue': {
      routes: 'Calendar Week'
      views: never
    }
    'src/pages/calendar/year.vue': {
      routes: 'Calendar Year'
      views: never
    }
    'src/pages/constellations/index.vue': {
      routes: 'Constellations'
      views: never
    }
    'src/pages/constellations/[month].vue': {
      routes: 'Constellations Month'
      views: never
    }
    'src/pages/holiday.vue': {
      routes: 'Holiday'
      views: never
    }
    'src/pages/moon-phase.vue': {
      routes: 'Moon Phase'
      views: never
    }
    'src/pages/onboarding.vue': {
      routes: 'Onboarding'
      views: never
    }
    'src/pages/search.vue': {
      routes: 'Search'
      views: never
    }
    'src/pages/settings.vue': {
      routes: 'Settings'
      views: never
    }
    'src/pages/summoning-day.vue': {
      routes: 'Summoning Day'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
